### ISSUE TITLE
mettre à jour le diagramme de class (voir commentaire)

### ISSUE THREAD

**Issue by ganeis** [inkaran77/Instalite#12]
Mettre toute les méthodes en majuscule

ajouter : 
- GetPassword dans ProfileManager
- Connexion dans User
- SignUp dans User

**Comment by inkaran77** [comment]
Modifier dans class User et Er Diagramm : 
Id ----> UserId

**Comment by inkaran77** [comment]
Modifier dans diagramme class Post et Er Diagramm :
- ajouter Author: String pour Post
- modifier Author: User -> Author: String  pour class Like et Comment 
car on va récupere le UserId donc pas bessoin de recuperer tout l'objet User

**Comment by inkaran77** [comment]
Modifier dans diagramme class Photo et ER Diagram:
 - Image : Image ---> String : UrlPhoto

**Comment by inkaran77** [comment]
Modifications effectuées
