### ISSUE TITLE
Alert()

### ISSUE THREAD

**Issue by inkaran77** [inkaran77/Instalite#22]
Bug réglé à 50%
Pour connexion: alerte vous êtes connecté affiché 2fois
Pour inscription : 
- pour connexion reussie 
=> Vérifier votre login/mot de passe 2 fois puis vous êtes connecté 2 fois 

- pour connexion erroné
=> Vérifier votre login/mot de passe 2 fois puis problème serveur 2 fois

**Comment by ganeis** [comment]
ok
